sn_read:
  - "adb devices"
root:
  - "adb root"
remount:
  - "adb remount"
raw_image_mode:
  - "adb shell setprop persist.vendor.ovr.camera.raw_image_mode 0"
enable_3a:
  - "adb shell setprop persist.vendor.camera.rgb.enable_3a false"
output_yuv:
  - "adb shell setprop persist.vendor.camera.teton.output_yuv false"
ovr_cmmv2:
  - "adb shell setprop persist.vendor.ovr.camera.cmmv2 1"
ovr_rgbocal:
  - "adb shell setprop persist.ovr.tracking.rgbocal false"
grid_line_frequency:
  - "adb shell oculuspreferences --set electric_grid_line_frequency 60"
factory_tool:
  - "adb shell syncboss_ht_factory_tool S -w 1"
guardian_disable:
  - "adb shell setprop persist.oculus.guardian_disable 1"
consumers_ctl_restart:
  - "adb shell syncboss_consumers_ctl restart"
mrsystemservice:
  - "adb shell sleep 5 adb shell stop mrsystemservice"
trackingfidelityservice:
  - "adb shell stop trackingfidelityservice"
wifi_disable:
  - "adb shell svc wifi disable"
prox_close:
  - "adb shell am broadcast -a com.oculus.vrpowermanager.prox_close"
adb_vrs-recorder:
  - 'adb shell "vrs-recorder --duration 385 --cmm_recorded_purposes  worldTracking/iot --slam_dynamic_exposure --cmm_allowed_mux_modes=worldTracking/lowLightController --log_stdout  --warmup 1000 --output=/data/local/tmp/test_rec.vrs --debug"'
adb_pull_vrs:
  - "adb pull /data/local/tmp/test_rec.vrs [local_vrs_path]"




